### ISSUE TITLE
Question: Additonal words in red at the end of all functions

### ISSUE THREAD

**Issue by rpherman** [thehappycheese/uiua-keypad#5]
After all the functions and & words in the keyboard window, there are a few dozen words in red like: "e i NAN W MaxInt Os Family Arch ExeExt DllExt Sep ThisFile...." etc. What are these for? Is this being pulled from somewhere else? Thank you! Great keyboard otherwise.

**Comment by thehappycheese** [comment]
> After all the functions and & words in the keyboard window, there are a few dozen words in red

Hi @rpherman Thankyou I am glad you are geting some use from it 😁 

The red words are [constants](https://www.uiua.org/docs/constants) that are part of Uiua (I think they are technically functions that take no arguments and return one value to the stack)

They are automatically extracted from the Uiua source code itself; When this extention is built it compiles a small Rust executable that includes the `uiua` crate... this is then executed (at build time only) to update the metadata used to render this keypad.

In more recent versions there are a lot more system functions and a lot more constants... it has made the button layout not quite as nice as it was in the past. It is already quite challenging to accomodate various screen sizes and aspect ratios without any hidden buttons.
